#!/bin/sh

DAEMON=/usr/sbin/httpd
NAME=httpd
DESC="Busybox HTTP Daemon"
HTTPROOT="/srv/www"
HTTP_ARGS="-h $HTTPROOT"

# Allow customizations from a config file
test -r /etc/default/httpd && . /etc/default/httpd

start() {
	echo -n "starting $DESC: $NAME... "
        if [ ! -d $HTTPROOT ]; then
                echo "$HTTPROOT is missing."
                exit 1
        fi
        start-stop-daemon -S -b -n $NAME -a $DAEMON -- $HTTP_ARGS
	echo "done."
}

stop() {
	echo -n "stopping $DESC: $NAME... "
	start-stop-daemon -K -n $NAME
	echo "done."
}

restart() {
    stop
    start
}

test -f $DAEMON || exit 0

set -e

case "$1" in
    start|stop|restart)
        "$1"
	;;
    reload)
	echo -n "reloading $DESC: $NAME... "
	killall -HUP $(basename ${DAEMON})
	echo "done."
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
	;;
esac

exit 0
