#!/bin/sh


# Call all init scripts in /etc/init.d
# executing them in reverse order.
#
for i in $(ls -r /etc/init.d/S??*) ; do

     # Ignore dangling symlinks (if any).
     [ ! -f ${i} ] && continue

     # Fork subprocess.
     ${i} stop
done
