#!/bin/sh

DAEMON="syslogd"
DAEMONFILE="/usr/sbin/$DAEMON"
PIDFILE="/var/run/$DAEMON.pid"

SYSLOGD_ARGS=""

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"


start() {
	printf 'Starting %s: ' "$DAEMON"

	SYSLOGD_ARGS="-P ${PIDFILE} ${SYSLOGD_ARGS}"
	start-stop-daemon --start --background \
		--pidfile "$PIDFILE" --exec "$DAEMONFILE" \
		-- $SYSLOGD_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"

	start-stop-daemon --stop --pidfile "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

wait_() {
	while start-stop-daemon --stop --test --quiet \
		--pidfile "$PIDFILE"; do
		sleep 0.1
	done
}

restart() {
	stop
	wait_
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
